# Generated by Django 5.2.1 on 2025-06-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smalltalk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='smalltalk/cover_pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='smalltalk/profile_pics'),
        ),
    ]
