# Generated by Django 5.2.1 on 2025-06-02 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smalltalk', '0002_alter_user_cover_pic_alter_user_profile_pic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='smalltalk/profile_pics')),
                ('cover_pic', models.ImageField(blank=True, null=True, upload_to='smalltalk/cover_pics')),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to='smalltalk.profile')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='smalltalk.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
