# Generated by Django 5.2.1 on 2025-06-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smalltalk', '0003_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
