# Generated by Django 5.2.1 on 2025-06-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smalltalk', '0004_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
