# Generated by Django 5.2.1 on 2025-06-04 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smalltalk', '0005_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='first_name',
        ),
    ]
