# Generated by Django 5.2.1 on 2025-06-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smalltalk', '0006_rename_username_profile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
    ]
