# Generated by Django 5.2.1 on 2025-06-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smalltalk', '0011_post_original_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
