# Generated by Django 5.2.1 on 2025-06-11 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smalltalk', '0012_post_is_shared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_shared',
        ),
        migrations.RemoveField(
            model_name='post',
            name='original_post',
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smalltalk.post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposted_post', to='smalltalk.post')),
            ],
            bases=('smalltalk.post',),
        ),
    ]
