# Generated by Django 5.2.1 on 2025-06-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smalltalk', '0014_alter_post_options_post_shared_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared_user',
        ),
    ]
